packages:
  - apps/*
  - tools/*
  - packages/*

catalog:
  typescript: 5.8.2
  tsup: ^8.5.0
  '@types/node': ^24.0.12
  zod: ^4.0.0

catalogs:
  trpc:
    '@trpc/server': ^11.4.3
    'trpc-cli': ^0.9.2

publicHoistPattern:
  - '*prettier*'
  - eslint
