packages:
  - apps/*
  - tools/*
  - packages/*

catalog:
  '@types/node': ^24.1.0
  tsup: ^8.5.0
  typescript: 5.8.2
  zod: ^4.0.14

catalogs:
  trpc:
    '@trpc/server': ^11.4.3
    trpc-cli: ^0.9.2

publicHoistPattern:
  - '*prettier*'
  - eslint
