packages:
  - apps/*
  - tools/*
  - packages/*

catalog:
  '@types/node': ^24.2.0
  tsup: ^8.5.0
  typescript: 5.9.2
  zod: ^4.0.14

catalogs:
  trpc:
    '@trpc/server': ^11.4.4
    trpc-cli: ^0.10.2

publicHoistPattern:
  - '*prettier*'
  - eslint
